language: android
android:
    components:
        - build-tools-19.1.0
        - android-14
        - sys-img-armeabi-v7a-android-19

script:
    - ./HomeSafe/gradlew test

notifications:
    email:
        recipients:
          - homesafeapp@googlegroups.com
        on_success: change
        on_success: change
